apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-primary
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aceest
      release: primary
  template:
    metadata:
      labels:
        app: aceest
        release: primary
    spec:
      containers:
      - name: aceest
        image: <DOCKERHUB_USERNAME>/aceest-fitness1:stable
        ports:
        - containerPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aceest
      release: canary
  template:
    metadata:
      labels:
        app: aceest
        release: canary
    spec:
      containers:
      - name: aceest
        image: <DOCKERHUB_USERNAME>/aceest-fitness1:canary
        ports:
        - containerPort: 5000
