# deployment-blue.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aceest
      track: blue
  template:
    metadata:
      labels:
        app: aceest
        track: blue
    spec:
      containers:
      - name: aceest
        image: <DOCKERHUB_USERNAME>/aceest-fitness1:vBlue  # tag for blue
        ports:
        - containerPort: 5000
---
# deployment-green.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aceest
      track: green
  template:
    metadata:
      labels:
        app: aceest
        track: green
    spec:
      containers:
      - name: aceest
        image: <DOCKERHUB_USERNAME>/aceest-fitness1:vGreen  # tag for green
        ports:
        - containerPort: 5000
