apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-rolling
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aceest
      strategy: rolling
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: aceest
        version: v1
    spec:
      containers:
      - name: aceest
        image: <DOCKERHUB_USERNAME>/aceest-fitness:latest
        ports:
        - containerPort: 5000
